spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ipVPNDb
    username: postgres
    password: 2357
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
